
---------------  DESDE SYSTEM ---------------

-- 1) Creamos el tablespace sobre el que va a operar el usuario MITUBO

CREATE TABLESPACE MITUBO_TS DATAFILE 'MITUBO_TS.DBF' SIZE 10M AUTOEXTEND ON;

-- 2) Creamos el usuario mitubo

CREATE USER MITUBO IDENTIFIED BY mitubo
  -- TEMPORARY TABLESPACE temp_ts      -- TABLESPACE PARA LOS SEGMENTOS TEMPORALES
  DEFAULT TABLESPACE MITUBO_TS         -- TABLESPACE POR DEFECTO PARA SUS OBJETOS
  QUOTA 100M ON MITUBO_TS;             -- MÁXIMO ESPACIO EN ESE TABLESPACE
  -- QUOTA 500K ON data_ts;
  -- PROFILE Perfil_1;                 -- ASIGNA EL Perfil_1 AL usuarios
  
-- 3) Creamos el perfil de conexión a la BD MiTubo

CREATE PROFILE PERFIL_CONEXION LIMIT
  -- SESSIONS_PER_USER 3               -- MÁXIMO NÚM. DE SESIONES PARA ESE USUARIO
  -- CONNECT_TIME UNLIMITED            -- DURACIÓN MÁXIMA DE LA CONEXIÓN (MINUTOS)
  IDLE_TIME 5                          -- MINUTOS DE TIEMPO MUERTO EN UNA SESIÓN
  FAILED_LOGIN_ATTEMPTS 3;             -- Nº MÁX. DE INTENTOS PARA BLOQUEAR CUENTA
  -- PASSWORD_LIFE_TIME 90             -- Nº DE DÍAS DE EXPIRACIÓN DE LA CONTRASEÑA
  -- PASSWORD_GRACE_TIME 3;            -- PERIODO DE GRACIA DESPUÉS DE LOS 90 DÍAS

-- 4) Le asigno el perfil a mitubo

ALTER USER MITUBO PROFILE PERFIL_CONEXION;

-- 5) Creamos un rol para el usuario mitubo, de modo que pueda operar con tablas,
-- conectarse a la base de datos, y dar permisos.

CREATE ROLE R_MITUBO;

GRANT CONNECT TO R_MITUBO WITH ADMIN OPTION;                                 -- AQUÍ LE DEJAMOS QUE SE CONECTE A LA BBDD

GRANT CREATE ROLE TO R_MITUBO WITH ADMIN OPTION;                             -- AQUÍ LE DEJAMOS CREAR ROLES

GRANT DROP ANY ROLE TO R_MITUBO WITH ADMIN OPTION;                           -- AQUÍ LE DEJAMOS BORRAR CUALQUIER ROL 

GRANT CREATE USER, DROP USER TO R_MITUBO WITH ADMIN OPTION;                  -- AQUÍ LE DEJAMOS CREAR Y ELMIMIAR USUARIOS

GRANT CREATE ANY VIEW TO R_MITUBO WITH ADMIN OPTION;                         -- AQUI LE DAMOS PERMISOS PARA CREAR VISTAS

GRANT ALTER ANY ROLE TO R_MITUBO WITH ADMIN OPTION;

GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, DELETE ANY TABLE,   -- AQUÍ LE DAMOS TODOS LOS PERMISOS SOBRE TABLAS
INSERT ANY TABLE, SELECT ANY TABLE, EXECUTE ANY PROCEDURE
TO R_MITUBO WITH ADMIN OPTION;                                               

GRANT CREATE TABLE, CREATE VIEW TO R_MITUBO WITH ADMIN OPTION;

GRANT RESOURCE TO R_MITUBO;   -- AQUÍ LE DAMOS PERMISOS SOBRE TODOS LOS OBJETOS

-- 6) Le damos el rol de R_MITUBO al usuario MITUBO

REVOKE CREATE TABLE FROM R_MITUBO;

GRANT R_MITUBO TO MITUBO;

--------------- DESDE MITUBO ---------------

-- 7) Lo primero que hacemos es crear el rol Administrador

CREATE ROLE R_ADMIN;

GRANT CONNECT TO R_ADMIN WITH ADMIN OPTION;                                  -- AQUÍ LE DEJAMOS QUE SE CONECTE A LA BBDD

GRANT CREATE TABLE, CREATE VIEW TO R_ADMIN WITH ADMIN OPTION;                -- LE DAMOS EL ROL DE CREAR TABLAS

GRANT CREATE ROLE TO R_ADMIN;                                                -- QUE PUEDA CREAR ROLES

GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, DELETE ANY TABLE,   -- AQUÍ LE DAMOS TODOS LOS PERMISOS SOBRE TABLAS
INSERT ANY TABLE, SELECT ANY TABLE, EXECUTE ANY PROCEDURE
TO R_ADMIN;
                  
GRANT DROP ANY ROLE, ALTER ANY ROLE TO R_ADMIN;           -- AQUÍ LE DEJAMOS BORRAR CUALQUIER ROL 

GRANT CREATE USER, DROP USER TO R_ADMIN;                  -- AQUÍ LE DEJAMOS CREAR Y ELMIMIAR USUARIOS

GRANT CREATE ANY VIEW TO R_ADMIN;                         -- AQUÍ LE DEJAMOS CREAR CUALQUIER VISTA

-- 8) Creamos el usuario ADMINISTRADOR

CREATE USER ADMINISTRADOR IDENTIFIED BY administrador 
    -- TEMPORARY TABLESPACE temp_ts      -- TABLESPACE PARA LOS SEGMENTOS TEMPORALES
  DEFAULT TABLESPACE MITUBO_TS           -- TABLESPACE POR DEFECTO PARA SUS OBJETOS
  QUOTA 100M ON MITUBO_TS;               -- MÁXIMO ESPACIO EN ESE TABLESPACE
  -- QUOTA 500K ON data_ts;
  PROFILE PERFIL_CONEXION;               -- ASIGNA EL Perfil_1 AL usuarios
  
-- 9) Le damos el rol R_ADMIN a ADMINISTRADOR 
  
GRANT R_ADMIN TO ADMINISTRADOR;

--------------- DESDE ADMINISTRADOR ---------------

-- 10)